lane_detector:
  ros__parameters:
    white_lower_lims: [0, 0, 200]
    white_upper_lims: [179, 25, 255]
    focus_area: [0.5, 0.0, 1.0, 1.0]
    line_angle_limit: 25.0
    lane_width: 1.0
    offset: 0.15
    lookahead: 2.5
    close_to_line_thres: 0.2
    going_right: False
    image_fps: 60